service: ${opt:service, 'logging-demo'}

frameworkVersion: '2'

provider:
  name: azure
  runtime: nodejs12
  region: ${opt:region, 'West Europe'}
  stage: ${opt:stage, 'dev'}
  type: 'Consumption'

plugins:
  - serverless-azure-functions
  - serverless-webpack

package:
  exclude:
    - local.settings.json
    - .vscode/**

functions:
  log:
    handler: src/controllers/Log.Log
    events:
      - http: true
        x-azure-settings:
          name: req
          methods:
            - POST
          authLevel: anonymous
      - http: true
        x-azure-settings:
          name: $return
          direction: out